### ISSUE TITLE
Rework onboarding by highlighting a single tutorial

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#26] opened 2018-08-23 15:12 UTC
@joelgrus is working on creating a new introductory tutorial.  Once we have that, we want to re-work the tutorial page so a single tutorial is highlighted, with links out to the more advanced tutorials.

**Comment by aaronsarnat** [comment] 2018-08-28 21:50
Duplicate of https://github.com/allenai/allennlp-website/issues/59 (Moving from demo board to website board)

**Closed by aaronsarnat** 2018-08-28 21:50 UTC
