### ISSUE TITLE
Add a link to the demo corresponding with each model

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#16] opened 2018-08-21 18:05 UTC
On https://allennlp.org/models we list each of the models, but don't have any way of connecting back to the demo.

![image](https://user-images.githubusercontent.com/954798/44420138-02e04480-a532-11e8-9a84-c5d3095abf27.png)

We could add a forth "button" that opens a window an pulls up the corresponding demo for that model.

**Comment by aaronsarnat** [comment] 2018-08-28 22:02
Duplicate of https://github.com/allenai/allennlp-website/issues/60 (moving from demo board to website board)

**Closed by aaronsarnat** 2018-08-28 22:02 UTC
