### ISSUE TITLE
Add namespace to sentiment analysis model config and upload new model

### ISSUE THREAD

**Issue by gagb** [allenai/allennlp-demo#401] opened 2020-05-04 22:25 UTC
Hi,

The [usage instructions](https://demo.allennlp.org/sentiment-analysis) result in an error. I am not sure what the fix is. You can reproduce it using the following steps:

1. Create a new conda environment and installed AllenNLP:
`pip install allennlp==1.0.0rc3 allennlp-models==1.0.0rc3`
 
2. Run the example code:
```
from allennlp.predictors.predictor import Predictor
import allennlp_models.sentiment
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz")
predictor.predict(
  sentence="a very well-made, funny and entertaining picture."
)
```

Here's the error message I get. `run.py` contains code in step #2:
```
File "run.py", line 4, in <module>
    print(predictor.predict(
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/predictors/text_classifier.py", line 25, in predict
    return self.predict_json({"sentence": sentence})
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 66, in predict_json
    return self.predict_instance(instance)
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 189, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/models/model.py", line 141, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/models/model.py", line 167, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/models/basic_classifier.py", line 171, in make_output_human_readable
    [
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/models/basic_classifier.py", line 172, in <listcomp>
    self.vocab.get_token_from_index(token_id.item(), namespace=self._namespace)
  File "/home/bansalg/miniconda2/envs/bert3/lib/python3.8/site-packages/allennlp/data/vocabulary.py", line 665, in get_token_from_index
    return self._index_to_token[namespace][index]
KeyError: 102
```

**Comment by matt-gardner** [comment] 2020-05-04 23:15
Closing as duplicate of https://github.com/allenai/allennlp/issues/4192.  You can see an updated model there that you should use instead.

**Comment by gagb** [comment] 2020-05-04 23:30
@matt-gardner thanks for replying quickly. Appreciate it.

That model is for SNLI??

That = https://storage.googleapis.com/allennlp-public-models/snli-roberta-large-2020.04.30.tar.gz

**Comment by matt-gardner** [comment] 2020-05-04 23:43
Ah, sorry, I went too quickly and misread a part of what you said.  It's the same underlying issue, but yeah, that's the wrong model.  It doesn't look like we've fixed that model yet, that I can see. 
@dirkgr, is there a new model for this one that I missed?  I'm going to reopen (and rename) this until we've gotten a new model uploaded for SST.

You can fix this locally by making the same change in the model's config file as you see here: https://github.com/allenai/allennlp-models/pull/37/files.  Do something like this:

```
wget https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz
tar -xzf sst-roberta-large-2020.02.17.tar.gz
# Edit config.json, as was done in the link above
tar -czf sst-roberta-large-2020.02.17-fixed.tar.gz config.json weights.th vocabulary/

# Your python prediction code, but passing in a local filename instead of the URL
```

**Comment by dirkgr** [comment] 2020-05-05 00:25
> @dirkgr, is there a new model for this one that I missed?

If it's not in `models.json`, there is not. If the fix is this easy though, I'll just make an update right now.

**Closed** 2020-05-06 00:44 UTC
