### ISSUE TITLE
Replace ‘pane’ layout with simplified flex layout

### ISSUE THREAD

**Issue by jonborchardt** [allenai/allennlp-demo#156] opened 2019-02-18 18:25 UTC
- The pane logic is larger than it needs to be and probably a bit brittle, flex is simple to do this
- Medium effort
- Medium benefit

**Comment by jonborchardt** [comment] 2019-02-18 18:39
from: Sam Skjonsberg 
Might also be worth looking at cssgrid for this stuff. Not sure if it's as well supported across browsers, but seems like it might be really useful for the proposed layout.

**Comment by schmmd** [comment] 2020-02-27 18:58
Closing as duplicate of https://github.com/allenai/allennlp-demo/issues/299

**Closed by schmmd** 2020-02-27 18:58 UTC
